---
title: "R Notebook"
output: html_notebook
---

Setup:

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(readxl)
library(rgeos)
library(pxR)
library(rjson)
library(rgdal)
library(maps)
library(rmapshaper)
setwd("C:/Users/brown/Desktop/swiss_data_maps")
```

Get data:

```{r}
ga_halb_orig <- read_xlsx("ga_and_halbtax/data.xlsx")
plzo_plz_name <- st_read("spatial/postcodes/PLZO_PLZ.shp")
pop_orig <- read.px("population/population.px")
pop_norm <- read_xlsx("population/population.xlsx", sheet = 1, skip = 2)
postcode_lookup_orig <- read_tsv("postcode_lookup/data.txt",
                            col_names = FALSE)
lookup_colnames <- read_tsv("postcode_lookup/readme.txt",
                            col_names = FALSE) %>%
  filter(str_detect(X1, "[:space:][:space:][:space:][:space:][:punct:]")) %>%
  separate(X1, sep = "\\:", into = c("name", "desc")) %>%
  pull(name)

sw_gbd <- "spatial/ArcGIS_D/ArcGIS_D/Schienennetz_LV03_20171210.gdb"
subset(ogrDrivers(), grepl("GDB", name))
fc_list <- ogrListLayers(sw_gbd)
print(fc_list)

swiss_network <- readOGR(dsn=sw_gbd,layer="Netzsegment") %>%
  st_as_sf()
```

Simplify the boundary data ...

```{r fig.height = 10, fig.width=15}
simp_swiss <- plzo_plz_name %>%
  select(PLZ) %>%
  rmapshaper::ms_simplify(keep = 0.05) %>% 
  mutate(PLZ = as.numeric(PLZ))
```

Simplify the railways data:

```{r}
rail_simp <- swiss_network %>%
# filter(AnzahlStreckengleise > 1) %>%
  select() %>%
  rmapshaper::ms_simplify(keep = 0.05)

tmap_mode("view")
tm_shape(rail_simp) +
  tm_lines()
```

Processs postcode data:

```{r}
names(postcode_lookup_orig) <- lookup_colnames

postcode_lookup <- postcode_lookup_orig %>%
  select(PLZ = 2,
         place_name = 3,
         kanton = 4)
```


Process the halbtax data:

```{r}
ga_halb <- ga_halb_orig %>%
  as_tibble() %>%
  dplyr::rename(PLZ = "PLZ_NPA",
         year = "Jahr_An_Anno",
         ga_total = "GA_AG",
         ht_total = "HTA_ADT_meta-prezzo",
         ga_imp_flag = "GA_AG_flag",
         ht_imp_flag = "HTA_ADT_meta-prezzo_flag") %>%
  mutate(PLZ = as.numeric(PLZ))
```

Process the population data:

```{r}
names <- c("year", "household_size", "area", "households")

pop <- pop_orig %>%
  as.data.frame() %>%
  as_tibble() %>%
  mutate_if(is.factor, as.character)

names(pop) <- names

pop_by_plz <- pop %>%
  mutate(PLZ = case_when(
    str_detect(area, "\\.\\.\\.\\.\\.\\.[:digit:][:digit:][:digit:][:digit:]") 
    ~ as.numeric(str_extract(area, "(?<=\\.\\.\\.\\.\\.\\.)[:digit:][:digit:][:digit:][:digit:]"))),
    area_name = str_remove(area, "\\.\\.\\.\\.\\.\\.[:digit:][:digit:][:digit:][:digit:][:space:]"),
    year = as.numeric(year)) %>%
  filter(!is.na(PLZ),
         household_size == "Haushaltsgrösse - Total") %>%
  select(-area)

pop_2019 <- pop_by_plz %>%
  filter(year == 2019)
```

Process other set of population data:

```{r}
pop_new_norm <- pop_norm %>%
  select(PLZ = 1,
         pop_total = Total) %>%
  filter(str_detect(PLZ, "[:digit:][:digit:][:digit:][:digit:]")) %>%
  mutate(PLZ = as.numeric(PLZ))
```

Join with the spatial data and process:

```{r fig.height = 10, fig.width=15}
subset <- ga_halb %>%
  filter(year == 2019)

swiss_2019 <- simp_swiss %>%
  left_join(subset, by = "PLZ") %>%
  left_join(pop_new_norm, by = "PLZ") %>%
  left_join(postcode_lookup, by = "PLZ") %>%
  mutate(ga_percent = case_when(is.na(ga_imp_flag) ~ round((ga_total/pop_total)*100, 1)),
         ht_percent = case_when(is.na(ht_imp_flag) ~ round((ht_total/pop_total)*100, 1)))

swiss_2019 %>%
  arrange(desc(ga_percent))
```

Get lakes:
(source: https://www.worldwildlife.org/publications/global-lakes-and-wetlands-database-large-lake-polygons-level-1)

```{r}
swiss_outline <- simp_swiss %>%
  summarise(country = "SWITZERLAND")

setwd("C:/Users/brown/Desktop/swiss_data_maps")
dir <- "spatial/lakes/"
file <- "glwd_1.shp"
lakes_1 <- st_read(paste0(dir, file)) %>%
  st_set_crs(4326) %>%
  st_transform(crs = 21781) %>%
  st_filter(swiss_outline, .predicate = st_intersects) %>%
  select()

file <- "glwd_2.shp"
lakes_2 <- st_read(paste0(dir, file)) %>%
  st_set_crs(4326) %>%
  st_transform(crs = 21781) %>%
  st_filter(swiss_outline, .predicate = st_intersects) %>%
  select()

swiss_lakes <- bind_rows(lakes_1, lakes_2) %>%
  st_intersection(swiss_outline)

tm_shape(simp_swiss) +
  tm_polygons() +
tm_shape(swiss_lakes) +
  tm_polygons(col = "lightblue")
```

Get just Zurich:

```{r}
swiss_2019 %>%
  filter(str_detect(kanton, "Zürich"))
```



Plot:

```{r fig.width=15, fig.height=12}
# summary(swiss_2019$ga_percent)

vars <- seq(0, 11, by = 1) %>%
  as_tibble() %>%
  dplyr::rename(breaks = 1) %>%
  mutate(label =  case_when(breaks ==  0 ~ "Less than 1%",
                            breaks == 10 ~ "More than 10%",
                                    TRUE ~ paste0(as.character(breaks), "%")))

breaks <- vars %>% pull(breaks)
labels <- vars[1:11,] %>% pull(label)

cities <- world.cities %>%
  filter(country.etc == "Switzerland",
         pop > 30000,
         !name %in% c("Koniz", "Vernier") ) %>%
  st_as_sf(coords = c("long", "lat"),
           crs = 4326) %>%
  st_transform(crs = st_crs(21781))

credits <- "For adults, GA costs 3,612 EUR per year\n
            Postcode area is spatial unit\n
            Data all open:\n
            Rail pass ownership and boundaries from\n
            Swiss Federal Statistical Office (2020)\n
            Cities from maps()\n
            Rail lines from Swiss Federal Office of Transport\n
            Built using tmap() and sf()\n
            Author: Christopher C Brown (2020)"

tmap_mode("plot")
map <- 
  tm_shape(swiss_2019) +
   tm_fill(col     = "ga_percent",
           palette = "Reds",
           labels  = labels,
           breaks  = breaks,
           title   = "Percent of population") +
  tm_shape(rail_simp) +
   tm_lines(col  = "grey90",
           alpha = 0.5,
           lwd   = 2) +
  tm_shape(swiss_lakes) +
   tm_fill(col = "lightblue") +
  tm_shape(cities) +
   tm_text(text     = "name",
           bg.color = "grey60",
           bg.alpha = 0.2) +
  tm_credits(credits,
           align    = "right",
           bg.color = "grey60",
           bg.alpha = 0.5,
           position = c("right", "top")) +
  tm_layout(frame    = FALSE,
          main.title = "Unlimited rail pass ('GA') ownership in Switzerland")

map

# tmap_save(map,
#          filename = "map.png",
#          width = 3300,
#          height = 3000,
#          units = "px")
```


```{r}
lakes <- map_data('lakes') %>%
  st_as_sf(coords = c("long", "lat")) %>%
  st_cast("POLYGON")





map('world')
map('lakes', add=TRUE, fill=TRUE, col='blue', boundary='black') %>%
  st_as_sf()
```

